import React from "react";

export default function TermsPage() {
	return (
		<div className="min-h-screen bg-black text-white pt-[80px] lg:pt-[130px] pb-20">
			<div className="max-w-7xl mx-auto px-6 md:px-8">
				{/* Header */}
				<div className="text-center mb-16">
					<h1 className="text-4xl md:text-5xl font-bold mb-4">
						Terms & Condition
					</h1>
					<p className="text-gray-400 text-sm">
						Last Updated: 19 November, 2025
					</p>
				</div>

				{/* Content Sections */}
				<div className="space-y-8">
					{/* Agreement to Terms */}
					<section>
						<h2 className="text-2xl font-bold mb-4">Agreement to Terms</h2>
						<p className="text-gray-300 leading-relaxed">
							By accessing and using TryOn360, you agree to be bound by these
							Terms of Use and all applicable laws and regulations. If you do
							not agree with any of these terms, you are prohibited from using
							or accessing this app. These terms govern your use of this app and
							any services we provide.
						</p>
					</section>
					<div className="border-t border-[#4B4B4B]"></div>

					{/* Service Description */}
					<section>
						<h2 className="text-2xl font-bold mb-4">Service Description</h2>
						<p className="text-gray-300 leading-relaxed">
							TryOn360 is a lifestyle application that uses artificial
							intelligence to apply virtual changes to user-uploaded
							photographs. Our features include the ability to simulate
							different hair styles, hair colors, and beard styles on a
							user&apos;s face. All results are for visualization or novelty
							purposes and are not professional recommendations.
						</p>
					</section>
					<div className="border-t border-[#4B4B4B]"></div>

					{/* User Content and AI Processing */}
					<section>
						<h2 className="text-2xl font-bold mb-4">
							User Content and AI Processing
						</h2>
						<div className="space-y-4 text-gray-300">
							<p className="leading-relaxed">
								<span className="font-semibold">Uploaded Photos:</span> When you
								upload a photograph, you grant TryOn360 a temporary,
								non-exclusive license to use, reproduce, and modify that photo
								solely for the purpose of generating your requested
								&quot;Try-On&quot; result. We do not claim ownership of your
								photos.
							</p>
							<p className="leading-relaxed">
								<span className="font-semibold">Data Retention:</span> We do not
								permanently store original or AI-generated photos on our servers
								after the generation process is complete, unless explicitly
								saved to your local device history.
							</p>
							<p className="leading-relaxed">
								<span className="font-semibold">Content Responsibility:</span>{" "}
								You are solely responsible for all photos you upload and must
								ensure you have the necessary rights to store and process those
								images (e.g., photos of minors or third parties).
							</p>
						</div>
					</section>
					<div className="border-t border-[#4B4B4B]"></div>

					{/* Prohibited Uses */}
					<section>
						<h2 className="text-2xl font-bold mb-4">Prohibited Uses</h2>
						<p className="text-gray-300 leading-relaxed">
							You agree not to use TryOn360 to upload, generate, or share any
							content that is unlawful, harmful, threatening, abusive,
							defamatory, vulgar, or obscene, or content that infringes upon the
							rights of others.
						</p>
					</section>
					<div className="border-t border-[#4B4B4B]"></div>

					{/* Disclaimers */}
					<section>
						<h2 className="text-2xl font-bold mb-4">Disclaimers</h2>
						<div className="space-y-4 text-gray-300">
							<p className="leading-relaxed">
								<span className="font-semibold">As-Is Service:</span> TryOn360
								is provided &quot;as-is.&quot; We set up, the face
								transformation and feedback we receive for fun and
								shouldn&apos;t be taken as professional advice. We can&apos;t
								promise that all the styles we provide is spot on or reliable.
							</p>
							<p className="leading-relaxed">
								<span className="font-semibold">No Warranty:</span> Our website
								is here for you &quot;as is &quot;no guarantees, either way. We
								can&apos;t promise it&apos;ll always be up and running or that
								it&apos;s completely free of bugs or viruses.
							</p>
						</div>
					</section>
					<div className="border-t border-[#4B4B4B]"></div>

					{/* Limitation of Liability */}
					<section>
						<h2 className="text-2xl font-bold mb-4">Limitation of Liability</h2>
						<div className="space-y-4 text-gray-300">
							<p className="leading-relaxed">
								The results generated by our AI are simulations. TryOn360 makes
								no warranties, expressed or implied, regarding the accuracy,
								completeness, or reliability of the hair, color, or beard
								simulations. Use the app at your own discretion.
							</p>
							<p className="leading-relaxed">
								To the maximum extent permitted by applicable law, TryOn360
								shall not be liable for any indirect, incidental, special,
								consequential, or punitive damages, or any loss of profits or
								revenues.
							</p>
						</div>
					</section>
					<div className="border-t border-[#4B4B4B]"></div>

					{/* Governing Law */}
					<section>
						<h2 className="text-2xl font-bold mb-4">Governing Law</h2>
						<p className="text-gray-300 leading-relaxed">
							These terms and conditions are governed by and construed in
							accordance with the laws of [Your Jurisdiction], and you
							irrevocably submit to the exclusive jurisdiction of the courts in
							that location.
						</p>
					</section>
					<div className="border-t border-[#4B4B4B]"></div>

					{/* Contact Us */}
					<section>
						<h2 className="text-2xl font-bold mb-4">Contact Us</h2>
						<p className="text-gray-300 leading-relaxed">
							If you have any questions about these terms, please contact us at {" "}
							<a
								href="mailto:support@vector360bd.com"
								className="text-blue-400 underline"
							>
								support@vector360bd.com
							</a>
						</p>
					</section>
				</div>
			</div>
		</div>
	);
}
