/** Shared input placeholders for admin and auth forms. */
export const formPlaceholders = {
  fullName: "Enter full name",
  email: "Enter your email address",
  phoneNumber: "01XXXXXXXXX",
  password: "Enter your password",
  title: "Enter title",
  description: "Enter description",
  linkUrl: "Enter link URL",
  newsLink: "Enter news link URL",
  bannerLink: "Enter banner link URL",
  galleryLink: "Enter gallery link URL",
  profileLink: "Enter profile link URL",
  club: "Enter club name",
  worldRanking: "Enter world ranking",
  points: "Enter points",
  eventName: "Enter event name",
  eventTypeName: "Enter event type name",
  eventAddress: "Enter event address",
  latitude: "Enter latitude",
  longitude: "Enter longitude",
  mission: "Enter federation mission",
  vision: "Enter federation vision",
  history: "Enter federation history",
  presidentMessage: "Enter president's message",
  selectFormat: "Select format",
  selectGender: "Select gender",
  selectEventType: "Select event type",
  selectGalleryType: "Select gallery type",
  selectGalleryCategory: "Select category",
  faqQuestion: "Enter the question",
  faqAnswer: "Enter the answer",
  designation: "Enter designation",
} as const
